// DEV-TIME generator (not run in prod). Classifies the whole exercise library into the Physical
// Therapy Lens taxonomy (movement pattern + primary joints) using the ONE shared classifier in
// src/lib/features/physicalTherapyTaxonomy.ts, and emits prisma/exercise-taxonomy.sql — an
// idempotent additive seed the entrypoint applies on every boot, so both fresh AND existing DBs
// gain the metadata. Because the classifier is a best-effort heuristic and the columns are
// editable, the seed only fills rows that are still NULL (WHERE "movementPattern" IS NULL), so a
// hand-corrected classification is never clobbered on the next boot.
//
//   npx tsx prisma/seed/buildTaxonomy.ts          # report only (coverage summary)
//   npx tsx prisma/seed/buildTaxonomy.ts --write  # emit prisma/exercise-taxonomy.sql
//
// Inputs: the base library is parsed out of prisma/seed-data.sql (the pg dump); the kettlebell
// add-on is read from its reviewed JSON catalog. Both key on the stable Exercise "sourceId".
import fs from "node:fs";
import path from "node:path";
import { inferTaxonomy } from "../../src/lib/features/physicalTherapyTaxonomy";

const ROOT = path.join(__dirname, "..");
const SEED = path.join(ROOT, "seed-data.sql");
const KETTLEBELL = path.join(__dirname, "data", "kettlebell.json");
const OUT = path.join(ROOT, "exercise-taxonomy.sql");
const write = process.argv.includes("--write");

const esc = (s: string) => s.replace(/'/g, "''");

type Row = { sourceId: number; name: string; muscle: string };

/** Parse MuscleGroup + Exercise INSERTs out of the seed dump. Names are single-quoted with ''
 *  escapes, so the name capture matches until an unescaped quote — robust to commas/parens. */
function parseSeed(sql: string): Row[] {
  const mgById = new Map<number, string>();
  const mgRe = /INSERT INTO public\."MuscleGroup" \(id, "sourceId", name\) VALUES \((\d+), (\d+), '([^']*)'\)/g;
  for (let m; (m = mgRe.exec(sql)); ) mgById.set(Number(m[1]), m[3]);

  const rows: Row[] = [];
  const exRe = /INSERT INTO public\."Exercise" \([^)]*\) VALUES \((\d+), (\d+|NULL), '((?:[^']|'')*)', (\d+),/g;
  for (let m; (m = exRe.exec(sql)); ) {
    if (m[2] === "NULL") continue; // custom exercises have no sourceId — nothing stable to key on
    rows.push({ sourceId: Number(m[2]), name: m[3].replace(/''/g, "'"), muscle: mgById.get(Number(m[4])) ?? "" });
  }
  return rows;
}

const MG_BY_SOURCE: Record<number, string> = {
  1: "Chest", 2: "Back", 3: "Triceps", 4: "Biceps", 5: "Shoulders", 6: "Quads",
  7: "Glutes", 8: "Hamstrings", 9: "Calves", 10: "Traps", 11: "Forearms", 12: "Abs",
};

function parseKettlebell(): Row[] {
  const cat = JSON.parse(fs.readFileSync(KETTLEBELL, "utf8")) as { sourceId: number; name: string; muscleGroupSourceId: number }[];
  return cat.map((e) => ({ sourceId: e.sourceId, name: e.name, muscle: MG_BY_SOURCE[e.muscleGroupSourceId] ?? "" }));
}

function main() {
  const rows = [...parseSeed(fs.readFileSync(SEED, "utf8")), ...parseKettlebell()];

  const L: string[] = [
    "-- Generated by prisma/seed/buildTaxonomy.ts — do not edit by hand.",
    "-- Idempotent additive seed: fills the Physical Therapy Lens taxonomy (movement pattern +",
    "-- primary joints) for library exercises, keyed on the stable \"sourceId\". Guarded by",
    "-- WHERE \"movementPattern\" IS NULL so a hand-corrected classification is never overwritten.",
    "-- Applied on every boot by docker-entrypoint.sh (fresh AND existing DBs).",
    "",
  ];

  let classified = 0;
  const byPattern = new Map<string, number>();
  for (const r of rows) {
    const { pattern, joints } = inferTaxonomy(r.name, r.muscle);
    if (!pattern) continue; // leave unmapped rows NULL → "Unclassified" everywhere, no UPDATE
    classified++;
    byPattern.set(pattern, (byPattern.get(pattern) ?? 0) + 1);
    L.push(
      `UPDATE public."Exercise" SET "movementPattern" = '${pattern}', "primaryJoints" = '${esc(JSON.stringify(joints))}' WHERE "sourceId" = ${r.sourceId} AND "movementPattern" IS NULL;`,
    );
  }

  const summary = [...byPattern.entries()].sort().map(([p, n]) => `${p}:${n}`).join(" · ");
  console.log(`library: ${rows.length} exercises · ${classified} classified · ${rows.length - classified} unclassified`);
  console.log(`  ${summary}`);

  if (write) {
    fs.writeFileSync(OUT, L.join("\n") + "\n");
    console.log(`wrote ${L.length} lines -> ${path.relative(process.cwd(), OUT)}`);
  } else {
    console.log("(report only — pass --write to emit prisma/exercise-taxonomy.sql)");
  }
}

main();
