// DEV-TIME generator (not run in prod). Reads the reviewed kettlebell catalog +
// template designs (prisma/seed/data/kettlebell{,-templates}.json) and emits
// prisma/kettlebell.sql — an idempotent additive seed the entrypoint applies on every
// boot, so kettlebell exercises + programs land on both fresh AND existing databases
// (the main seed-data.sql only loads into an empty DB).
//
//   npx tsx prisma/seed/buildKettlebell.ts          # report only
//   npx tsx prisma/seed/buildKettlebell.ts --write  # emit prisma/kettlebell.sql
//
// Idempotency:
//   • Exercise rows   — ON CONFLICT ("sourceId") DO NOTHING
//   • Template row    — ON CONFLICT (key) DO NOTHING
//   • TemplatePriority — ON CONFLICT ("templateId","muscleGroupId") DO NOTHING (its @@unique)
//   • TemplateDay/Slot — WHERE NOT EXISTS on the natural (parent, position) tuple
// Children resolve their parent id by lookup (key / position), never by a hard-coded PK,
// so a re-run (or a fresh autoincrement) can't duplicate or mis-link rows.
import fs from "node:fs";
import path from "node:path";

const DATA = path.join(__dirname, "data");
const OUT = path.join(__dirname, "..", "kettlebell.sql");
const write = process.argv.includes("--write");

const VALID_MG = new Set([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]);

type Exercise = {
  sourceId: number;
  name: string;
  muscleGroupSourceId: number;
  exerciseType: string;
  instructions: string[];
  youtubeId: string | null;
};
type Slot = { muscleGroupSourceId: number; exerciseSourceId: number | null };
type Day = { label: string | null; slots: Slot[] };
type Template = {
  sourceId: number;
  key: string;
  name: string;
  emphasis: string;
  description: string | null;
  sex: string;
  frequency: number;
  priorities: Record<string, string>; // muscleGroupSourceId -> MgPriority
  days: Day[];
};

const readJson = <T,>(f: string): T => JSON.parse(fs.readFileSync(path.join(DATA, f), "utf8")) as T;
const esc = (s: string) => s.replace(/'/g, "''");
const sqlStr = (s: string | null) => (s == null ? "NULL" : `'${esc(s)}'`);

function validate(exercises: Exercise[], templates: Template[]) {
  const errors: string[] = [];
  const exIds = new Set(exercises.map((e) => e.sourceId));
  for (const e of exercises) {
    if (!VALID_MG.has(e.muscleGroupSourceId)) errors.push(`exercise ${e.sourceId} bad muscleGroupSourceId ${e.muscleGroupSourceId}`);
    if (e.exerciseType !== "kettlebell") errors.push(`exercise ${e.sourceId} exerciseType ${e.exerciseType} (expected kettlebell)`);
  }
  for (const t of templates) {
    const slotMgs = new Set(t.days.flatMap((d) => d.slots.map((s) => s.muscleGroupSourceId)));
    for (const m of Object.keys(t.priorities)) {
      if (!VALID_MG.has(Number(m))) errors.push(`${t.key}: bad priority mg ${m}`);
      if (!slotMgs.has(Number(m))) errors.push(`${t.key}: priority mg ${m} has no slot`);
    }
    for (const d of t.days)
      for (const s of d.slots) {
        if (!VALID_MG.has(s.muscleGroupSourceId)) errors.push(`${t.key}: slot bad mg ${s.muscleGroupSourceId}`);
        if (s.exerciseSourceId != null && !exIds.has(s.exerciseSourceId)) errors.push(`${t.key}: slot references unknown exercise ${s.exerciseSourceId}`);
      }
  }
  if (errors.length) {
    console.error("VALIDATION FAILED:\n  " + errors.join("\n  "));
    process.exit(1);
  }
}

function buildSql(exercises: Exercise[], templates: Template[]): string {
  const L: string[] = [
    "-- Generated by prisma/seed/buildKettlebell.ts — do not edit by hand.",
    "-- Idempotent additive seed (ON CONFLICT / WHERE NOT EXISTS); applied on every boot by",
    "-- docker-entrypoint.sh so kettlebell exercises + programs reach fresh AND existing DBs.",
    "-- sourceId bands: exercises 900000–909999, templates 910000–919999.",
    "",
    "-- ===== Exercises =====",
  ];

  for (const e of exercises) {
    const notes = sqlStr(e.instructions?.length ? JSON.stringify(e.instructions) : null);
    L.push(
      `INSERT INTO public."Exercise" ("sourceId", name, "muscleGroupId", "exerciseType", "youtubeId", notes, "isCustom", "userId")`,
      `SELECT ${e.sourceId}, ${sqlStr(e.name)}, mg.id, 'kettlebell', ${sqlStr(e.youtubeId)}, ${notes}, false, NULL`,
      `FROM public."MuscleGroup" mg WHERE mg."sourceId" = ${e.muscleGroupSourceId}`,
      `ON CONFLICT ("sourceId") DO NOTHING;`,
    );
  }

  for (const t of templates) {
    const k = sqlStr(t.key);
    L.push("", `-- ===== Template: ${t.key} =====`);
    // Parent
    L.push(
      `INSERT INTO public."Template" ("sourceId", key, name, emphasis, description, sex, frequency, "userId")`,
      `VALUES (${t.sourceId}, ${k}, ${sqlStr(t.name)}, ${sqlStr(t.emphasis)}, ${sqlStr(t.description)}, ${sqlStr(t.sex)}, ${t.frequency}, NULL)`,
      `ON CONFLICT (key) DO NOTHING;`,
    );
    // Priorities (guarded by the real @@unique)
    for (const [mg, prio] of Object.entries(t.priorities)) {
      L.push(
        `INSERT INTO public."TemplatePriority" ("templateId", "muscleGroupId", priority)`,
        `SELECT t.id, mg.id, '${prio}' FROM public."Template" t`,
        `JOIN public."MuscleGroup" mg ON mg."sourceId" = ${mg}`,
        `WHERE t.key = ${k}`,
        `ON CONFLICT ("templateId", "muscleGroupId") DO NOTHING;`,
      );
    }
    // Days + slots
    t.days.forEach((d, di) => {
      L.push(
        `INSERT INTO public."TemplateDay" ("templateId", "position", label)`,
        `SELECT t.id, ${di}, ${sqlStr(d.label)} FROM public."Template" t WHERE t.key = ${k}`,
        `  AND NOT EXISTS (SELECT 1 FROM public."TemplateDay" d WHERE d."templateId" = t.id AND d."position" = ${di});`,
      );
      d.slots.forEach((s, si) => {
        const exJoin = s.exerciseSourceId != null
          ? `LEFT JOIN public."Exercise" ex ON ex."sourceId" = ${s.exerciseSourceId}`
          : "";
        const exSel = s.exerciseSourceId != null ? "ex.id" : "NULL";
        L.push(
          `INSERT INTO public."TemplateSlot" ("templateDayId", "position", "muscleGroupId", "exerciseId")`,
          `SELECT d.id, ${si}, mg.id, ${exSel} FROM public."Template" t`,
          `JOIN public."TemplateDay" d ON d."templateId" = t.id AND d."position" = ${di}`,
          `JOIN public."MuscleGroup" mg ON mg."sourceId" = ${s.muscleGroupSourceId}`,
          ...(exJoin ? [exJoin] : []),
          `WHERE t.key = ${k}`,
          `  AND NOT EXISTS (SELECT 1 FROM public."TemplateSlot" s WHERE s."templateDayId" = d.id AND s."position" = ${si});`,
        );
      });
    });
  }
  return L.join("\n") + "\n";
}

function main() {
  const exercises = readJson<Exercise[]>("kettlebell.json");
  const templates = readJson<Template[]>("kettlebell-templates.json");
  validate(exercises, templates);

  const totalSlots = templates.reduce((n, t) => n + t.days.reduce((m, d) => m + d.slots.length, 0), 0);
  console.log(`catalog: ${exercises.length} exercises · ${templates.length} templates · ${totalSlots} slots — validation OK`);

  const sql = buildSql(exercises, templates);
  if (write) {
    fs.writeFileSync(OUT, sql);
    console.log(`wrote ${sql.split("\n").length} lines -> ${path.relative(process.cwd(), OUT)}`);
  } else {
    console.log("(report only — pass --write to emit prisma/kettlebell.sql)");
  }
}

main();
